### ISSUE TITLE
Doesn't want to load the icon for some reason

### ISSUE THREAD

**Issue by Xamusel** [nekoyoubi/yep_util#1]
I'm using a Windows 10 rig, and it won't load the icon file for some reason, which I find absolutely confusing.

**Comment by nekoyoubi** [comment]
Usually this is because the script is being ran in a way that doesn't allow the icon to be found in the current working directory, which should always be the same directory that the script is in in order for it to work properly. I've had this problem when trying to run AHK scripts from batch files or other apps. Are you just double-clicking the .ahk to launch, or do you have a different setup?

**Comment by Xamusel** [comment]
I thought it was a .exe file? I was under the impression that it would work by double-clicking on it.

**Comment by nekoyoubi** [comment]
Oh, you're not seeing the icon load from the .exe? That's interesting. May be a problem with my build. Give me a few to check it out. To be honest, I only ever run the .ahk, so it may be an issue I just never found. Worst case scenario, it's not pulling the icon from the .exe and still looking to the folder. This could be fixed by dropping the .ico in the same folder as the .exe before running it. Let me see what I can find out. Thanks for the heads-up.

**Comment by Xamusel** [comment]
You're welcome. Happy to help you out with this.

**Comment by Xamusel** [comment]
...so it seems that the .ico file was needed in the same folder after all.

**Comment by nekoyoubi** [comment]
Thanks for the update. I've removed the icon assignment before building the binaries, so the new ones should work without the need for the .ico now. Thanks again.

**Comment by Xamusel** [comment]
You're welcome.
