### ISSUE TITLE
Error at line 111

### ISSUE THREAD

**Issue by itsaruse** [nekoyoubi/yep_util#8]
Bug Report

Plugin Name: YEP AutoUpdater

Error Message:
"Error at line 111
Line Text: Personal </a>     <a href="/open-source" class="js-selected-navigation-item nav-item nav-item ope...
Error: This line does not contain a recognized action.

The program will exit.

How to Replicate Bug: 
I just downloaded the newest version of autohotkey and this plugin today. At first I got an error at line 1 but it was just a quotation mark error that I fixed when I opened the code. However, I'm not sure how to fix this error. I try to run the auto-updater and this is what I keep getting.

**Comment by nekoyoubi** [comment]
Since I haven't updated this in a bit, at first I thought maybe Yanfly had updated his page to something the updater couldn't recognize, so I did a forced update. I got no such error. The only thing I can think is that your downloaded .ahk is somehow corrupt, you've changed the URL in config that you're using to find the latest (default still works `http://yanfly.moe/yep/changelog/`), or there was a moment where something wasn't working on his site.

That being said, I also looked at his changelog's source looking for "Personal" and found nothing, so I'm assuming it's one of the first options.

Try copying just the .ahk to another folder, running it, and if you absolutely have to, change the path to your extraction tool in the newly generated .config file, but don't change the `ChangelogURL`.

Let me know if that works or doesn't for you, and worst case scenario I can get you into Discord and we can troubleshoot.

**Comment by itsaruse** [comment]
Well i re-downloaded to a new folder, and now i'm getting the error at line 1 again, I'll try and fix that with the proper quotation marks, but I'm guessing it'll end up erroring at line 111 again...

**Comment by itsaruse** [comment]
this is really really weird, I change the ' to " at line 1 this time trying the fix I did last time and now I still have a "left most character is illegal" error. BTW, neither of the .exe files work for me either. I'm running windows 8.1, why is that?

**Comment by itsaruse** [comment]
I'm sorry man, I think I left out some info, I was discussing this on another forum early and got confused. When I very first ran this I got an error at line 1 saying 'utf the left most character is illegal, I changed that ' on 'utf - 8' to "utf - 8" and that's when I got the line 111 error, now on the new download I can't get past the line 1 error. Again, sorry for the confusion, its late, lol

**Comment by itsaruse** [comment]
hey man, I got up early this morning and tried copying the raw code instead of just downloading the file and it worked, don't know what's wrong with the downloaded file. Cheers!

**Comment by nekoyoubi** [comment]
Given the fact that you had something on line 1 that even mentioned "utf - 8", you've obviously not downloaded the .ahk correctly, as you can see the contents of the .ahk don't include that string.

I'm glad you got it working, but I'm thinking this may have just been a case of not being familiar with Github. For just downloading the .ahk file, you would want to navigate to that file, then click the "Raw" button which send you to https://raw.githubusercontent.com/nekoyoubi/yep_util/master/yep_autoupdate/yep_autoupdate.ahk  You can save that file as is and not have any issues.

As for not being able to run the binaries, Windows 8.1 wouldn't be an issue, no. Roughly ~500 unique people come and download this every couple of weeks, and I've seen no one have an issue with the binaries on any Windows operating system thus far.

Either way, I'm glad you got it working. Cheers.

**Comment by nekoyoubi** [comment]
Now that I think about it, I think your issue with the binaries may be the same as your issue with the loose script. Just download it from the main archive and you should be golden: https://github.com/nekoyoubi/yep_util/archive/master.zip
